external_components:
  - source:
      type: local
      path: components
    components: [snk_mower]

esphome:
  name: test-mower
  friendly_name: Test Mower

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  baud_rate: 0
  level: INFO

wifi:
  ssid: testssid
  password: testpass123
  # enabled by default, no need for extra config

api:

ota:
  - platform: esphome

uart:
  id: mower_uart
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 230400

snk_mower:
  id: my_mower
  uart_id: mower_uart
  pin: "9633"
  display_clk: 18
  display_mosi: 23
  display_cs: 5

  battery_level:
    name: "Battery Level"
  battery_voltage:
    name: "Battery Voltage"
  error_code:
    name: "Error Code"
  is_mowing:
    name: "Mowing"
  is_charging:
    name: "Charging"
  is_docked:
    name: "Docked"
  has_error:
    name: "Has Error"

button:
  - platform: template
    name: "Start Mowing"
    icon: mdi:play
    on_press:
      - lambda: 'id(my_mower)->start_mowing();'

  - platform: template
    name: "Return to Dock"
    icon: mdi:home-import-outline
    on_press:
      - lambda: 'id(my_mower)->return_to_dock();'

sensor:
  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 5min

bluetooth_proxy:
  active: true
